config/routes.rb
RoleFinder::Application.routes.draw do

  resources :auditions

  devise_for :users
  root 'pages#marketing_home'
  get 'plays/json' => 'plays#index'
  get 'roles/json' => 'roles#index'
  get 'theatres/json' => 'theatres#index'
  get 'roles/full_json' => 'roles#full_index'
  get 'plays/full_json' => 'plays#full_index'
  get 'theatres/full_json' => 'theatres#full_index'
  get 'plays/json_all' => 'plays#all_index'
  get 'roles/json_for_plays' => 'roles#index_for_plays'
  get 'actors/search' => 'actors#search'
  get 'roles/json_search' => 'roles#search_index'
  get 'submissions/:audition_id' => 'submissions#index'
  get 'callsheets/:audition_id' => 'callsheets#index'

  resources :actors, only: [:show, :index]
  resources :jobs
  resources :submissions, only: [:create, :destroy]
  resources :callsheets, only: [:create, :update, :destroy]
  resources :plays, only: [:show, :index, :create, :update, :destroy]
  resources :roles, only: [:index, :create, :update, :destroy]
  resources :theatres, only: [:index, :create, :update, :destroy]

end

app/models/audition.rb
class Audition < ActiveRecord::Base
  belongs_to :theatre
  belongs_to :play
  has_many :submissions
  has_many :users, through: :submissions
  has_many :callsheets

  def equity_type
    if self.equity == true
      return "Equity"
    else
      return "Non-Equity"
    end
  end

  def star
    equity_star = 'fa-star'
    non_star = 'fa-star-o'
    if self.equity == true
      return equity_star
    else
      return non_star
    end
  end

end

app/controllers/auditions_controller.rb
class AuditionsController < ApplicationController
  before_action :set_audition, only: [:show, :edit, :update, :destroy]

  # GET /auditions
  # GET /auditions.json
  def index
    @auditions = Audition.all
    @submission = Submission.new
  end

  # GET /auditions/1
  # GET /auditions/1.json
  def show
    @submission = Submission.new
  end

  # GET /auditions/new
  def new
    @audition = Audition.new
  end

  # GET /auditions/1/edit
  def edit
  end

  # POST /auditions
  # POST /auditions.json
  def create
    @audition = Audition.new(audition_params)

    respond_to do |format|
      if @audition.save
        format.html { redirect_to @audition, notice: 'Audition was successfully created.' }
        format.json { render action: 'show', status: :created, location: @audition }
      else
        format.html { render action: 'new' }
        format.json { render json: @audition.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /auditions/1
  # PATCH/PUT /auditions/1.json
  def update
    respond_to do |format|
      if @audition.update(audition_params)
        format.html { redirect_to @audition, notice: 'Audition was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @audition.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /auditions/1
  # DELETE /auditions/1.json
  def destroy
    @audition.destroy
    respond_to do |format|
      format.html { redirect_to auditions_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_audition
      @audition = Audition.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def audition_params
      params.require(:audition).permit(:name, :description, :theatre_id, :equity, :audition_start, :audition_end, :play_id)
    end
end

app/helpers/auditions_helper.rb
module AuditionsHelper
end

app/views/auditions/_form.html.erb
<%= form_for(@audition) do |f| %>
  <% if @audition.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@audition.errors.count, "error") %> prohibited this audition from being saved:</h2>

      <ul>
      <% @audition.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :theatre_id %><br>
    <%= f.number_field :theatre_id %>
  </div>
  <div class="field">
    <%= f.label :equity %><br>
    <%= f.check_box :equity %>
  </div>
  <div class="field">
    <%= f.label :audition_start %><br>
    <%= f.date_select :audition_start %>
  </div>
  <div class="field">
    <%= f.label :audition_end %><br>
    <%= f.date_select :audition_end %>
  </div>
  <div class="field">
    <%= f.label :play_id %><br>
    <%= f.number_field :play_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/auditions/edit.html.erb
<h1>Editing audition</h1>

<%= render 'form' %>

<%= link_to 'Show', @audition %> |
<%= link_to 'Back', auditions_path %>

app/views/auditions/index.html.erb
<div class="all_auditions">

<h1>Chicago Auditions</h1>
  <div class="sidebar">
    <p>These are the current active auditions. As an actor, you can submit by clicking the button on this list, or by using the button on the audition's individual page.<br /><br />If you are a theatre company and want to post an audition, <span>click here.</span></p>
  </div>
<% @auditions.each do |audition| %>
  <div class="one_audition">
    <h2><%= link_to audition.play.title, audition_path(audition) %></h2>
    <ul>
      <li><%= audition.theatre.name %></li>
      <li><i class='fa <%= audition.star %>'></i> <%= audition.equity_type %></li>
      <li><%= audition.play.type_of_show %></li>
      <li>
        <% if user_signed_in? %>
          <% if Submission.where(audition_id: audition.id).find_by(user_id: current_user.id) %>
            <button type="button" class="submitted">Submitted!</button>
          <% else %>
            <%= form_for(@submission) do |f| %>
              <%= f.hidden_field :user_id, :value => current_user.id %>
              <%= f.hidden_field :audition_id, :value => audition.id %>
              <%= f.submit '✔︎ Submit', :confirm => "Submit for this audition?" %>
            <% end %>
          <% end %>
        <% else %>
          <button type="button"><%= link_to '✔︎ Submit'.html_safe, new_user_session_path %></button>
        <% end %>
      </li>
    </ul>
    <div class="description">
      <% start_day = audition.audition_start.strftime("%e").to_i %>
      <% end_day = audition.audition_end.strftime("%e").to_i %>
      <p><%= audition.audition_start.strftime("%A, %b") %> <%= start_day.ordinalize %> - <%= audition.audition_end.strftime("%A, %b") %> <%= end_day.ordinalize %></p>
      <p><span class="text"><%= audition.description %></span> <%= link_to "(Read more?)", audition_path(audition) %></p>
    </div>
  </div>
<% end %>
</div>

app/views/auditions/new.html.erb
<h1>New audition</h1>

<%= render 'form' %>

<%= link_to 'Back', auditions_path %>

app/views/auditions/show.html.erb
  <div class="single_audition_page">
    <h2><%= @audition.play.title %></h2>
    <div class="audition_info">
    <ul>
      <li><%= @audition.theatre.name %></li>
      <li><i class='fa <%= @audition.star %>'></i> <%= @audition.equity_type %> <%= @audition.play.type_of_show %></li>
      <li>Unpaid</li>
    </ul>
    <ul class="dates">
      <% start_day = @audition.audition_start.strftime("%e").to_i %>
      <% end_day = @audition.audition_end.strftime("%e").to_i %>
      <li><span>Auditions</span><br /><%= @audition.audition_start.strftime("%A, %b") %> <%= start_day.ordinalize %> - <%= @audition.audition_end.strftime("%A, %b") %> <%= end_day.ordinalize %></li>
      <li><span>Rehearsals</span><br />Tuesday, Aug 3rd - Wednesday, Sep 1st</li>
      <li><span>Run</span><br />Thursday, Sep 2nd - Sunday, Sep 30th</li>
      </ul>
        <div>
        <% if user_signed_in? %>
          <% if Submission.where(audition_id: @audition.id).find_by(user_id: current_user.id) %>
            <button type="button">Submitted!</button>
          <% else %>
            <%= form_for(@submission) do |f| %>
              <%= f.hidden_field :user_id, :value => current_user.id %>
              <%= f.hidden_field :audition_id, :value => @audition.id %>
              <%= f.submit '✔︎ Submit', :confirm => "Submit for this audition?" %>
            <% end %>
          <% end %>
        <% else %>
          <button type="button"><%= link_to '✔︎ Submit'.html_safe, new_user_session_path %></button>
        <% end %>
      </div>
      <button type="button"><%= link_to "Submissions", "/submissions/#{@audition.id}" %></button>
  </div>
    <div class="breakdown">
      <h3>Roles:</h3>
      <ul>
      <% roles = @audition.play.roles %>
      <% roles.each do |role| %>
        <li><%= role.character_name %></li>
      <% end %>
      </ul>
    </div>
    <div class="description">
      <p><%= @audition.description %></p>
    </div>


  </div>