config/routes.rb
RoleFinder::Application.routes.draw do

  resources :auditions

  devise_for :users
  root 'pages#marketing_home'
  get 'plays/json' => 'plays#index'
  get 'roles/json' => 'roles#index'
  get 'theatres/json' => 'theatres#index'
  get 'roles/full_json' => 'roles#full_index'
  get 'plays/full_json' => 'plays#full_index'
  get 'theatres/full_json' => 'theatres#full_index'
  get 'plays/json_all' => 'plays#all_index'
  get 'roles/json_for_plays' => 'roles#index_for_plays'
  get 'actors/search' => 'actors#search'
  get 'roles/json_search' => 'roles#search_index'
  get 'submissions/:audition_id' => 'submissions#index'
  get 'callsheets/:audition_id' => 'callsheets#index'

  resources :actors, only: [:show, :index]
  resources :jobs
  resources :submissions, only: [:create, :destroy]
  resources :callsheets, only: [:create, :update, :destroy]
  resources :plays, only: [:show, :index, :create, :update, :destroy]
  resources :roles, only: [:index, :create, :update, :destroy]
  resources :theatres, only: [:index, :create, :update, :destroy]

end

app/models/audition.rb
class Audition < ActiveRecord::Base
  belongs_to :theatre
  belongs_to :play
  has_many :submissions
  has_many :users, through: :submissions
  has_many :callsheets

  def equity_type
    if self.equity == true
      return "Equity"
    else
      return "Non-Equity"
    end
  end

  def star
    equity_star = 'fa-star'
    non_star = 'fa-star-o'
    if self.equity == true
      return equity_star
    else
      return non_star
    end
  end

end

app/models/callsheet.rb
class Callsheet < ActiveRecord::Base
  # validates_uniqueness_of :audition_id, :scope => :user_id
  belongs_to :user
  belongs_to :audition

  # def user
  #   User.find_by(id: self.audition_id)
  # end
end

app/models/job.rb
class Job < ActiveRecord::Base
  belongs_to :role
  belongs_to :user
  belongs_to :theatre

  # def play
  #   self.role.play
  # end

  # def play_title
  #   self.play.try(:title)
  # end

  # def play_title=(title)
  #   self.play = Play.find_or_create_by_title(title) if title.present?
  # end
  def is_number?(obj)
    obj.to_s == obj.to_i.to_s
  end


end

app/models/play.rb
class Play < ActiveRecord::Base
  has_many :roles
  has_many :auditions
end

app/models/role.rb
class Role < ActiveRecord::Base

  belongs_to :play

end

app/models/submission.rb
class Submission < ActiveRecord::Base
  validates_uniqueness_of :audition_id, :scope => :user_id
  belongs_to :user
  belongs_to :audition
end

app/models/theatre.rb
class Theatre < ActiveRecord::Base
  has_many :auditions
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :jobs
  has_many :roles, through: :jobs
  has_many :submissions
  has_many :auditions, through: :submissions
  has_many :callsheets

  mount_uploader :headshot, HeadshotUploader
  mount_uploader :resume, ResumeUploader

  def star
    equity_star = 'fa-star'
    emc_star = 'fa-star-half-o'
    non_star = 'fa-star-o'
    if self.equity == "Equity"
      return equity_star
    elsif self.equity == "EMC"
      return emc_star
    else
      return non_star
    end
  end

  # def self.search(search)

  #   if search
  #     if Role.find_by(id: search)
  #       where(self.roles.where(id: search))
  #     end
  #   end

  # end

end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :authenticate_user!

  def new
    @job = Job.new
  end

  def create
    @actor = User.find_by(params[:id])
    @jobs = @actor.jobs.order(:created_at)
    @job = Job.new

    # if params[:play_id] == nil
    #   play = Play.find_or_create_by(title: params[:plays_value])
    #   play.update_attributes(publix: false)

    #     Role.find_or_create_by(character_name: params[:roles_value]) do |role|
    #       role.play_id = play.id
    #       role.publix = false
    #     end

    # else

    #   if params[:role_id] == nil
    #     Role.find_or_create_by(character_name: params[:roles_value]) do |role|
    #       role.play_id = params[:play_id]
    #       @job.role_id = role.id
    #     end
    #   end

    # end



    role_id = params[:character_name]

    if role_id.is_a? Integer
      @job.role_id = role_id
    else
      play = Play.new
      play.title = params[:play_name]
      play.publix = false
      play.save
      role = Role.new
      role.play_id = play.id
      role.character_name = params[:character_name]
      role.publix = false
      role.save
      @job.role_id = role.id
    end

    theatre_name = params[:theatre_name]
    theatre = Theatre.find_by(name: theatre_name)
    @job.theatre_id = theatre.id
    @job.user_id = current_user.id

    respond_to do |format|
      if @job.save
        format.html { redirect_to root_path, notice: 'Job was successfully created.' }
        format.json { render json: @job, status: :created }
        format.js {}
      else
        format.html { render action: 'new' }
        format.json { render json: @job.errors, status: :unprocessable_entity }
        format.js {}
      end
    end

  end

  private

    def todo_params
      params.require(:job).permit(:role_id, :theatre_id, :user_id, :theatre_name, :character_name)
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def marketing_home
    render :layout => false
  end
end

app/controllers/plays_controller.rb
class PlaysController < ApplicationController
  before_action :authenticate_user!
  before_action :set_play, only: [:show, :update, :destroy]

  def index
    @public_plays = Play.where(publix: true)
    @plays = @public_plays.order(:title).where("title like ?", "%#{params[:term]}%")
    render json: @plays.map(&:title)
  end

  def full_index
    @plays = Play.order(:title).where(id: params[:term])
    render json: @plays.map()
  end

  def all_index
    @public_plays = Play.where(publix: true)
    @plays = @public_plays.order(:title).where(title: params[:term])
    render json: @plays.map()
  end

  def show
    @roles = @play.roles
  end

  def create
    @play = Play.new(play_params)
    @play.save
  end

  def update
    @play.update(play_params)
  end

  def destroy
    @play.destroy
  end

  private

    def set_play
      @play = Play.find(params[:id])
    end

    def play_params
      params.require(:play).permit(:title, :type_of_show, :author, :music_by)
    end

end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_role, only: [:update, :destroy]

  def index
    @roles = Role.order(:character_name).where("character_name like ?", "%#{params[:term]}%")
    @roles_with_shows = []
    @roles.each do |role|
      hash = { label: role.character_name, show: Play.find_by(id: role.play_id).title }
      @roles_with_shows.push(hash)
    end
    render json: @roles_with_shows.map()
  end

  def search_index
    @public_roles = Role.where(publix: true)
    @roles = @public_roles.order(:character_name).where("character_name like ?", "%#{params[:term]}%")
    @roles_with_shows = []
    @roles.each do |role|
      hash = { label: role.character_name, value: role.id, show: Play.find_by(id: role.play_id).title }
      @roles_with_shows.push(hash)
    end
    render json: @roles_with_shows.map()
  end

  def full_index
    @roles = Role.order(:character_name).where("id like ?", "%#{params[:term]}%")
    render json: @roles.map()
  end

  def index_for_plays
    @roles = Role.order(:character_name).where(play_id: params[:id]).where(character_name: params[:term])
    render json: @roles.map()
  end

  def create
    @role = Role.new(role_params)
    @role.save
  end

  def update
    @role.update(role_params)
  end

  def destroy
    @role.destroy
  end


  private

    def set_role
      @role = Role.find(params[:id])
    end

    def role_params
      params.require(:role).permit(:character_name, :play_id)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/auditions_helper.rb
module AuditionsHelper
end

app/helpers/callsheets_helper.rb
module CallsheetsHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/plays_helper.rb
module PlaysHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/submissions_helper.rb
module SubmissionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app="roleFinder">
<head>
  <title>RoleFinder</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => false %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => false %>
  <%= csrf_meta_tags %>
  <link href="//netdna.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
  <link href='http://fonts.googleapis.com/css?family=Comfortaa:400,700' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Lato:300,400,700' rel='stylesheet' type='text/css'>

</head>
<body>
  <div class="nav">
    <ul class="main">
        <li id="title"><span>CastMate</span></li>
        <li>About</li>
        <li><%= link_to "Auditions", auditions_path %></li>
        <li><%= link_to "Actor Search", actors_path %></li>
    </ul>
    <ul class="log">
      <% if user_signed_in? %>
        <li><%= link_to "Sign Out", destroy_user_session_path, method: 'delete' %></li>
      <% else %>
        <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <li><%= link_to "Sign In", new_user_session_path %></li>
      <% end %>
    </ul>
    <% if user_signed_in? %>
    <% @user = current_user %>
        <ul class="logged_in">
          <li><%= image_tag @user.headshot.thumb.url %></li>
          <li>Hello, <span><%= link_to @user.first_name, actor_path(@user) %></span></li>
        </ul>
    <% end %>
  </div>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>


<%= yield %>

</body>
</html>

app/views/pages/marketing_home.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RoleFinder</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <link href="//netdna.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
  <link href='http://fonts.googleapis.com/css?family=Comfortaa:400,700' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Lato:300,400,700' rel='stylesheet' type='text/css'>

</head>

<body>
<div class="marketing_home">
  <div class="banner">
    <%= link_to '<i class="fa fa-sign-in"></i>'.html_safe, new_user_session_path %>
<h1>Bring life to the stage with <span>CastMate</span></h1>

<h2>We makes it easier for theatre companies to receive actor submissions online</h2>
<h3>post auditions - receieve submissions - search and sort - create callsheets</h3>

<ul>
<li class="landing actor">I'm an actor</li>
<li class="landing theatre">I have a theatre company</li>
<li class="actor_intro"><i class="fa fa-times-circle"></i><br />As an actor, once you sign up you are able to simply submit for any of the auditions listed with a single click. To be the first to know when auditions are posted, enter your email below.</li>
<li class="actor_intro email"><span><i class="fa fa-envelope-o"></i></span><%= text_field_tag :actor_email %></li>
<li class="theatre_intro"><i class="fa fa-times-circle"></i><br />As a theatre company, you can post auditions and receive your submissions in a sortable list, adding anyone you are interested in to your call sheet. Wanna know when we're up and running? Give us your email.</li>
<li class="theatre_intro email"><span><i class="fa fa-envelope-o"></i></span><%= text_field_tag :theatre_email %></li>
</ul>

</div>
</div>
</body>

</html>